### ISSUE TITLE
PyPI deployment

### ISSUE THREAD

**Issue by skelly37** [SpamixOfficial/OpenClick#18]
Since it's a python program, how about being able to do `pip install openclick`? Going this way, AUR/.deb deployment would seem redundant (unless you want just to try and learn)

**Comment by SpamixOfficial** [comment]
Might be a good idea actually! I'll maybe do it, but I think the easiest and most user friendly way is to use a normal package manager, or flatpak. Since im planning on a GUI and an easy-to-use software, I think using a package manager will be more appealing to more users @skelly37

**Comment by skelly37** [comment]
Package managers/AUR are distro-dependent. They might be a bit more handy, that's true. But deploying it on `pip` makes you do one deploy for Windows/Mac/Linux/whatever `pip` supports.

And it's not a "cheat", you can find actually plenty of GUI desktop apps on PyPI, e.g. [Picard](https://pypi.org/project/picard/) ;)

**Comment by SpamixOfficial** [comment]
> Package managers/AUR are distro-dependent. They might be a bit more handy, that's true. But deploying it on `pip` makes you do one deploy for Windows/Mac/Linux/whatever `pip` supports instead of writing `PKGBUILD`, flatpaking it, creating some `apt` repository and whatever else might be useful.
> 
> And it's not a "cheat", you can find actually plenty of GUI desktop apps on PyPI, e.g. [Picard](https://pypi.org/project/picard/) ;)
> 
> Btw don't get me wrong, I'm not saying that you should drop plans to any other deploys than PyPI, I'm just suggesting what seems the easiest and most convenient approach to achieve as much as possible. Plenty is no plague hah

True! I still think I'll stick to my plans though ;D My goal with this project is to create a reliable autoclicker, that's also user-friendly (which also means, easy-to-install). 

Many new linux users that wants to play games often also want an autoclicker. We all have played cookie clicker with an autoclicker right? That is a bit harder on linux than windows because there aren't that many good linux-compatible autoclickers. 

My project though makes it easy for the new user to install and use the software!

Pip sounds great, but I think most new users doesn't even know what python is ;D

**Comment by SpamixOfficial** [comment]
@skelly37 Ill start by adding a GUI to my software, and then I'll add it to the package managers. Lastly, I might add it to pip.
